# Copyright 2025 Marcelo Parisi (github.com/feitnomore)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-push
  namespace: mnp-cicd
spec:
  description: Pushes to Git repository using alpine/git.
  params:
    - name: SUBDIRECTORY
      description: >-
        Relative path within the workspace where the repository should be cloned.
        If empty, clones to the root of the workspace.
      type: string
      default: ""
    - name: THIS_VERSION
      description: This version.
      type: string

  workspaces:
    - name: source
      description: The workspace where the Git repository will be cloned.

  steps:
    - name: push-with-alpine-git
      image: alpine/git:latest
      imagePullPolicy: Always
      env:
        - name: THIS_VERSION
          value: $(params.THIS_VERSION)
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: gh-credentials
              key: token
      workingDir: $(workspaces.source.path)/$(params.SUBDIRECTORY)
      script: |
        #!/bin/sh

        echo "--- ALPINE/GIT RELEASE SCRIPT START ---"

        git config --global credential.helper store
        echo "https://oauth2:${GITHUB_TOKEN}@github.com" > ~/.git-credentials

        if [ ${THIS_VERSION} != "dev" ]
        then
          git tag -a v${THIS_VERSION} -m "Release: ${THIS_VERSION}"
        fi

        git push origin main --tags

        echo "--- ALPINE/GIT RELEASE SCRIPT END ---"
