# Copyright 2025 Marcelo Parisi (github.com/feitnomore)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: virtctl-start-stop
  namespace: mnp-cicd
spec:
  description: Execs virtctl start/stop.
  params:
    - name: IMAGE_REGISTRY
      description: Image Registry.
      type: string
    - name: CLI_IMAGE_NAME
      description: Image name.
      type: string
    - name: CLI_IMAGE_TAG
      description: Image tag.
      type: string
    - name: THIS_LANE
      description: Lane to be stopped.
      type: string
    - name: THIS_CMD
      description: virtctl cmd start/stop.
      type: string

  workspaces:
    - name: shared-output
      description: "Workspace for storing logs and output files."

  steps:
    - name: execute
      image: $(params.IMAGE_REGISTRY)/$(params.CLI_IMAGE_NAME):$(params.CLI_IMAGE_TAG)
      imagePullPolicy: Always
      env:
        - name: THIS_LANE
          value: $(params.THIS_LANE)
        - name: THIS_CMD
          value: $(params.THIS_CMD)
      volumeMounts:
        - name: kubeconfigs
          mountPath: /root/.kube/
        - name: lane-config
          mountPath: /root/.config/
      workingDir: /
      script: |
        #!/bin/sh
        set -e

        echo "--- Lane: ${THIS_LANE} -> ${THIS_CMD} ---"
        
        PRINTABLE_STATUS=`/usr/local/bin/kubectl get vm lane-${THIS_LANE} -n mnp-cicd -o json | /usr/local/bin/jq -r '.status.printableStatus'`

        if [ ${THIS_CMD} = "start" ]
        then
          if [ ${PRINTABLE_STATUS} = "Stopped" ]
          then
            /usr/local/bin/virtctl ${THIS_CMD} lane-${THIS_LANE} -n mnp-cicd
          else 
            echo "lane-${THIS_LANE} not Stopped"
          fi
        elif [ ${THIS_CMD} = "stop" ]
        then
          if [ ${PRINTABLE_STATUS} = "Running" ]
          then
            /usr/local/bin/virtctl ${THIS_CMD} lane-${THIS_LANE} -n mnp-cicd
            /usr/local/bin/kubectl delete vmi lane-${THIS_LANE} -n mnp-cicd --grace-period=0
          else 
            echo "lane-${THIS_LANE} not Running"
          fi
        fi

  volumes:
    - name: kubeconfigs
      secret:
        secretName: lane-configs
        defaultMode: 0600
        items:
          - key: kubeconfig-1-31
            path: kubeconfig-1-31
          - key: kubeconfig-1-32
            path: kubeconfig-1-32
          - key: kubeconfig-1-33
            path: kubeconfig-1-33
          - key: kubeconfig-1-34
            path: kubeconfig-1-34
          - key: status
            path: status
    - name: lane-config
      configMap:
        name: lane-config
        items:
          - key: config.ini
            path: config.ini