# Copyright 2025 Marcelo Parisi (github.com/feitnomore)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: virtctl-start-stop
  namespace: mnp-cicd
spec:
  description: Execs virtctl start/stop.
  params:
    - name: IMAGE_REGISTRY
      description: The registry URL.
      type: string
    - name: CLI_IMAGE_NAME
      description: image name.
      type: string
    - name: CLI_IMAGE_TAG
      description: image tag.
      type: string
    - name: THIS_LANE
      type: string
    - name: THIS_CMD
      type: string

  workspaces:
    - name: docker-credentials
      description: "Docker credential"
      optional: true
    - name: shared-output
      description: "Workspace for storing logs and output files."

  tasks:
    - name: execute-virtctl
      taskRef:
        name: virtctl-start-stop
      params:
        - name: pipelinerun-name
          value: $(context.pipelineRun.name)
        - name: IMAGE_REGISTRY
          value: "$(params.IMAGE_REGISTRY)"
        - name: CLI_IMAGE_NAME
          value: $(params.CLI_IMAGE_NAME)
        - name: CLI_IMAGE_TAG
          value: $(params.CLI_IMAGE_TAG)
        - name: THIS_LANE
          value: $(params.THIS_LANE)
        - name: THIS_CMD
          value: $(params.THIS_CMD)
      workspaces:
        - name: shared-output
          workspace: shared-output

  finally: 
    - name: check-overall-status
      taskRef: { name: check-pipelinerun-status }
      params:
        - name: pipelinerun-name
          value: $(context.pipelineRun.name)
        - name: IMAGE_REGISTRY
          value: $(params.IMAGE_REGISTRY)
        - name: CLI_IMAGE_NAME
          value: $(params.CLI_IMAGE_NAME)
        - name: CLI_IMAGE_TAG
          value: "latest"
