# Copyright 2025 Marcelo Parisi (github.com/feitnomore)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ${PRE}build-infra-image-
  namespace: mnp-cicd
  labels:
    cicd/image: ${IMAGE}
    cicd/branch: ${BRANCH}
    cicd/project: ${PROJECT}
spec:
  pipelineRef:
    name: build-infra-images
  params:
    - name: INFRA_REPO_URL
      value: "${MNP_INFRA_GIT}"
    - name: infra-repo-project
      value: "${PROJECT}"
    - name: INFRA_REPO_BRANCH
      value: "${BRANCH}"
    - name: infra-repo-clone-subdir
      value: "${PROJECT}"
    - name: IMAGE_REGISTRY
      value: "${IMAGE_REGISTRY}"
    - name: CLI_IMAGE_NAME
      value: "${CLI_IMAGE_NAME}"
    - name: CLI_IMAGE_TAG
      value: "${CLI_IMAGE_TAG}"
    - name: ARTIFACTS_IMAGE_NAME
      value: "${ARTIFACTS_IMAGE_NAME}"
    - name: ARTIFACTS_IMAGE_TAG
      value: "${ARTIFACTS_IMAGE_TAG}"
    - name: GO_IMAGE_NAME
      value: "${GO_IMAGE_NAME}"
    - name: GO_IMAGE_TAG
      value: "${GO_IMAGE_TAG}"

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: "ceph-rbd-sc"
    - name: docker-credentials
      secret:
        secretName: repository-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: shared-output
      persistentVolumeClaim:
        claimName: cicd-output