# Copyright 2025 Marcelo Parisi (github.com/feitnomore)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Secret
metadata:
  name: lane-credentials
  namespace: mnp-cicd
type: Opaque
data:
  status: "my-status"
  kubeconfig-1-31: "<kubeconfig-contents>"
  kubeconfig-1-32: "<kubeconfig-contents>"
  kubeconfig-1-33: "<kubeconfig-contents>"
  ssh-priv: "<ssh-key-file>"
  known_hosts: "<ssh-known-hosts-file>"